version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: igloc
    main: ./cmd/igloc
    binary: igloc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: igloc
    repository:
      owner: O6lvl4
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/O6lvl4/igloc"
    description: "Scan your local machine and discover files ignored by .gitignore"
    license: "MIT"
    install: |
      bin.install "igloc"
    test: |
      system "#{bin}/igloc", "--version"
